# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  System.Debug: true
  NODE_TLS_REJECT_UNAUTHORIZED: '0'

pool:
 name: Default
#  demands:
#    - Agent.Name -equals UP636306

  
 

steps:
# - script: echo Hello, BEROE world!
#   displayName: 'Run a one-line BEROE script'


# - script: |
#     echo ScanCentral version check.
#     call scancentral -version
#     whoami
#     echo WI scan.
#     wi.exe -u http://zero.webappsecurity.com/ -c -ps 4 -w test -f test.pdf -gp -ag
#   displayName: 'Run BEROE scancentral version check & WI scan'

# - script: |
#     echo SCA & rules version check.
#     sourceanalyzer -version
#     fortifyupdate -showInstalledRules
#   displayName: 'Run BEROE sourceanalyzer and rulepack version check'

# - task: FortifyScanCentralSAST@7
#   inputs:
#     scanCentralClientToken: '$(ScanCentral.ClientToken)'
    # sscCiToken: '$(ScanCentral.SscCiToken)'
    # buildTool: 'none'


# ----------------------------
# Step 1: Start WebInspect API scan
# ----------------------------
- task: CmdLine@2
  displayName: 'Start SC DAST 26.2 API CICD scan'
  inputs:
    script: |
      echo Starting WebInspect API scan...
      curl -X POST "https://localhost:8888/api/v2/scans/start-scan-cicd" -H "accept: text/plain" -H "Authorization: FortifyToken ZDVjMDBhZmUtYTYxMy00ZDAzLTg5NjgtMjlkNmNlZjIyNzY3" -H "Content-Type: application/json" -d "{\"cicdToken\":\"833c5077-251b-43ab-8646-3b9aa13907f9\",\"name\":\"getAPItest6\"}" -k
      
      
      
- task: FortifyScanCentralDAST@7
  displayName: 'Start SC DAST 26.2 API CICD scan with PLUGIN'  
  inputs:
    scanCentralDastApiUrl: 'https://localhost:8888/api/v2'
    scanCentralCiCdToken: '833c5077-251b-43ab-8646-3b9aa13907f9'
    sscCiToken: 'ZDVjMDBhZmUtYTYxMy00ZDAzLTg5NjgtMjlkNmNlZjIyNzY3'

- task: CmdLine@2
  displayName: 'Start SC DAST 26.2 FCLI scan'
  inputs:
    script: |
      echo Starting FCLI DAST scan...
      fcli sc-dast scan start -n=SAMOBEROE -s=84c94cfe-af01-467d-be7b-21e3570dd189

